spring:
  profiles:
    active:
    - dev #当前使用的环境
---
server:
  port: 6001
spring:
  profiles: dev #开发环境
  application:
    name: config-client-dev
  rabbitmq:
    host: localhost
    port: 15672
    username: guest
    password: guest
  cloud:
    bus:
      enabled: true
    trace:
      enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://eureka01.com:1001/eureka/
  
upload:
  directory: D:/upload
  
      
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
---
server:
  port: 6002
spring:
  profiles: test #测试环境
  application:
    name: config-client-test
eureka:
  client:
    service-url:
      defaultZone: http://eureka01.com:1001/eureka/